name = "ARS"
uuid = "5744327c-528e-406a-a16f-961c23f1e1d8"
authors = ["Eliassj <elias.sjolin@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
MakieExt = "Makie"

[compat]
DocStringExtensions = "0.9.3"
ForwardDiff = "0.10.38"
Makie = "0.22.1"
SpecialFunctions = "2.5.0"
julia = "1.11"
