name = "ARS"
uuid = "5744327c-528e-406a-a16f-961c23f1e1d8"
authors = ["Eliassj <elias.sjolin@gmail.com> and contributors"]
version = "1.0.2-DEV"

[deps]
AdaptiveRejectionSampling = "c75e803d-635f-53bd-ab7d-544e482d8c75"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
AdaptiveRejectionSampling = "0.2.1"
Compat = "4.17.0"
DifferentiationInterface = "0"
DocStringExtensions = "0"
Mooncake = "0"
Random = "1"
SpecialFunctions = "2"
StatsBase = "0.34"
julia = "1"
